version: "2"

services:
  web:
    restart: on-failure:10
    build: .
    command: gunicorn service.wsgi:application --bind :4501 --reload
    volumes:
      - .:/code
    ports:
      - "4501:4501"
