version: "2"

services:
  web:
    restart: on-failure:10
    build: .
    command: gunicorn service.wsgi:application --bind :4500 --reload
    volumes:
      - .:/code
    ports:
      - "4500:4500"

volumes:
  db-data:
